config/routes.rb
Rails.application.routes.draw do
  get 'trades/index'
  resources :trades, only: [:index]

  get 'static_pages/root'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "trades#index"

  namespace :charts do
    get "count-by-week-trades"
    get "count-by-month-trades"
    get "average-price-by-week-trades"
    get "average-price-by-month-trades"
    get "volume-weighted-price-by-week-trades"
    get "volume-weighted-price-by-month-trades"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  
  def count_by_week_trades
    render json: Trade.group_by_week(:transaction_date).count
  end

  def count_by_month_trades
    render json: Trade.group_by_month(:transaction_date).count
  end

  def average_price_by_week_trades
    render json: Trade.group_by_week(:transaction_date).average(:price)
  end

  def average_price_by_month_trades
    render json: Trade.group_by_month(:transaction_date).average(:price)
  end

  def volume_weighted_price_by_week_trades
    # VWAP = (Sum(Qty * Price) / Sum(Qty)) I'm not sure I did this right
    @total = Trade.group_by_week(:transaction_date).sum(:total)
    @grouped_quantities = Trade.group_by_week(:transaction_date).sum(:quantity)

    vwaps = @grouped_quantities.zip(@total).map do |quantity, total|
      vwap = if quantity[1] == 0 # avoids division by zero
        0
      else
        [
          total[1] / quantity[1]
        ]
      end

      [
        quantity[0],
        vwap
      ]
    end
    render json: vwaps
  end

  def volume_weighted_price_by_month_trades
    # #VWAP = (Sum(Qty * Price) / Sum(Qty)) I'm not sure I did this right
    @total = Trade.group_by_month(:transaction_date).sum(:total)
    @grouped_quantities = Trade.group_by_month(:transaction_date).sum(:quantity)

    vwaps = @grouped_quantities.zip(@total).map do |quantity, total|
      vwap = if quantity[1] == 0 # avoids division by zero
        0
      else
        [
          total[1] / quantity[1]
        ]
      end

      [
        quantity[0],
        vwap
      ]
    end
    render json: vwaps
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def index
    @pagy, @trades = pagy(Trade.all)

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/charts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Charts</h1>

<div id="charts">
  <% @charts.each do |chart| %>
    <%= render chart %>
    <p>
      <%= link_to "Show this chart", chart %>
    </p>
  <% end %>
</div>

<%= link_to "New chart", new_chart_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercarisChart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/root.html.erb
<h1>StaticPages#root</h1>
<p>Find me in app/views/static_pages/root.html.erb</p>
<button type="button" class="btn btn-primary">Primary</button>

app/views/trades/index.html.erb
<div class="container">
  <div class="row mt-3">
      <div> 
        <i class="bi bi-bar-chart-fill"></i>
        <strong>MARKET PRICE</strong>
      </div>
    <p>Organic Wheat</p>
  </div>
    <div class="row py-3">
    <%= line_chart charts_average_price_by_month_trades_path, prefix: "$", round: 2, label: "Price", ytitle: "Monthly Average Price (USD)" %>
    </div>
    <div class="row py-3">
    <%= line_chart charts_volume_weighted_price_by_month_trades_path, prefix: "$", round: 2, label: "Price", ytitle: "Monthly WVAP (USD)" %>
    </div>
  <div class="row py-3">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Commodity</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price (USD)</th>
        </tr>
      </thead>
      <tbody>
        <% @trades.each do |trade| %>
          <tr>
            <td><%= trade.transaction_date.strftime("%m/%d/%Y")  %></td>
            <td><%= trade.contract %></td>
            <td><%= number_with_delimiter(trade.quantity, delimiter: ",") %></td>
            <td><%= number_to_currency(trade.price.to_f) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
</div>